/** @license ISC License (c) copyright 2016 original and current authors */
/** @author Ian Hofmann-Hicks (evil) */
/** @author Henrique Limas */

export * from './combinators'
export * from './logic'
export * from './predicates'

export { default as Arrow } from './Arrow/index'
export { default as Async } from './Async/index'
export { default as Const } from './Const/index'
export { default as Either } from './Either/index'
export { default as Equiv } from './Equiv/index'
export { default as Identity } from './Identity/index'
export { default as IO } from './IO/index'
export { default as List } from './List/index'
export { default as Maybe } from './Maybe/index'
export { default as Pair } from './Pair/index'
export { default as Pred } from './Pred/index'
export { default as Reader } from './Reader/index'
export { default as ReaderT } from './Reader/ReaderT'
export { default as Result } from './Result/index'
export { default as Star } from './Star/index'
export { default as State } from './State/index'
export { default as Tuple } from './Tuple/index'
export { default as Unit } from './Unit/index'
export { default as Writer } from './Writer/index'

export * from './helpers'

export { default as branch } from './Pair/branch'
export { default as fanout } from './Pair/fanout'
export { default as find } from './Maybe/find'
export { default as prop } from './Maybe/prop'
export { default as propPath } from './Maybe/propPath'
export { default as safe } from './Maybe/safe'
export { default as safeAfter } from './Maybe/safeAfter'
export { default as safeLift } from './Maybe/safeLift'
export { default as toPairs } from './Pair/toPairs'
export { default as tryCatch } from './Result/tryCatch'

export { default as All } from './All'
export { default as Any } from './Any'
export { default as Assign } from './Assign'
export { default as Endo } from './Endo'
export { default as First } from './First'
export { default as Last } from './Last'
export { default as Max } from './Max'
export { default as Min } from './Min'
export { default as Prod } from './Prod'
export { default as Sum } from './Sum'

export * from './pointfree'

export { default as evalWith } from './State/evalWith'
export { default as execWith } from './State/execWith'
export { default as fst } from './Pair/fst'
export { default as log } from './Writer/log'
export { default as nmap } from './Tuple/nmap'
export { default as project } from './Tuple/project'
export { default as race } from './Async/race'
export { default as read } from './Writer/read'
export { default as snd } from './Pair/snd'

export { default as arrayToList } from './List/arrayToList'
export { default as asyncToPromise } from './Async/asyncToPromise'
export { default as eitherToAsync } from './Async/eitherToAsync'
export { default as eitherToFirst } from './First/eitherToFirst'
export { default as eitherToLast } from './Last/eitherToLast'
export { default as eitherToMaybe } from './Maybe/eitherToMaybe'
export { default as eitherToResult } from './Result/eitherToResult'
export { default as firstToAsync } from './Async/firstToAsync'
export { default as firstToEither } from './Either/firstToEither'
export { default as firstToLast } from './Last/firstToLast'
export { default as firstToMaybe } from './Maybe/firstToMaybe'
export { default as firstToResult } from './Result/firstToResult'
export { default as lastToAsync } from './Async/lastToAsync'
export { default as lastToEither } from './Either/lastToEither'
export { default as lastToFirst } from './First/lastToFirst'
export { default as lastToMaybe } from './Maybe/lastToMaybe'
export { default as lastToResult } from './Result/lastToResult'
export { default as listToArray } from './List/listToArray'
export { default as maybeToAsync } from './Async/maybeToAsync'
export { default as maybeToEither } from './Either/maybeToEither'
export { default as maybeToFirst } from './First/maybeToFirst'
export { default as maybeToLast } from './Last/maybeToLast'
export { default as maybeToResult } from './Result/maybeToResult'
export { default as resultToAsync } from './Async/resultToAsync'
export { default as resultToEither } from './Either/resultToEither'
export { default as resultToFirst } from './First/resultToFirst'
export { default as resultToLast } from './Last/resultToLast'
export { default as resultToMaybe } from './Maybe/resultToMaybe'
export { default as tupleToArray } from './Tuple/tupleToArray'
export { default as writerToPair } from './Pair/writerToPair'
